"""Stochopia v3-spine training environment (Curriculum Level 0).

The deterministic core remains framework-neutral and contains no LLM calls or
Gymnasium dependency.  This package also exposes optional external CLI/API
policy adapters; they live outside ``StochopiaStructurerEnv.reset()/step()`` and
consume the same typed public boundary.
"""

from .core import ENVIRONMENT_VERSION, PRICING_VERSION, StochopiaStructurerEnv
from .agent_runner import (
    AGENT_PROMPT_VERSION,
    AGENT_REQUEST_SCHEMA,
    AGENT_RUN_SCHEMA,
    AgentActionError,
    AgentDecision,
    AgentEpisodeResult,
    AgentPolicy,
    AgentRequest,
    CommandAgentPolicy,
    LLMAgentPolicy,
    create_api_agent_policy,
    load_agent_system_prompt,
    parse_environment_action,
    run_agent_episode,
)
from .trajectory import (
    TRAJECTORY_FORMAT,
    TrajectoryEntry,
    TrajectoryMetadata,
    TrajectoryRecorder,
    verify_trajectory,
)
from .wrappers import ScalarizedStochopiaEnv
from .evaluation import (
    AGGREGATE_FORMAT,
    EVALUATION_FORMAT,
    TASK_SUITE_FORMAT,
    TaskSuite,
    aggregate_evaluations,
    load_evaluations,
    replay_and_evaluate,
    replay_and_evaluate_payload,
    save_evaluation_aggregate,
)
from .types import (
    REWARD_SCHEMA_VERSION,
    SCALARIZATION_VERSION,
    TASK_SCHEMA,
    TASK_VERSION,
    V3_PUBLIC_CLIENT_ALIAS,
    V3_PUBLIC_NOTIONAL_BASE,
    Action,
    AskClient,
    ConstraintSignals,
    EnvironmentAction,
    EpisodeTask,
    InvalidAction,
    Observation,
    RequestQuote,
    RewardComponents,
    RewardTerm,
    ScalarizationSpec,
    Skip,
    StepTransition,
    SubmitDesign,
    SubmitProduct,
    scalarize_reward,
)

__all__ = [
    "AGENT_REQUEST_SCHEMA",
    "AGENT_RUN_SCHEMA",
    "AGENT_PROMPT_VERSION",
    "ENVIRONMENT_VERSION",
    "EVALUATION_FORMAT",
    "PRICING_VERSION",
    "REWARD_SCHEMA_VERSION",
    "AGGREGATE_FORMAT",
    "SCALARIZATION_VERSION",
    "TASK_SCHEMA",
    "TASK_SUITE_FORMAT",
    "TASK_VERSION",
    "TRAJECTORY_FORMAT",
    "V3_PUBLIC_CLIENT_ALIAS",
    "V3_PUBLIC_NOTIONAL_BASE",
    "Action",
    "AgentActionError",
    "AgentDecision",
    "AgentEpisodeResult",
    "AgentPolicy",
    "AgentRequest",
    "AskClient",
    "CommandAgentPolicy",
    "ConstraintSignals",
    "EnvironmentAction",
    "EpisodeTask",
    "InvalidAction",
    "StochopiaStructurerEnv",
    "LLMAgentPolicy",
    "Observation",
    "RequestQuote",
    "RewardComponents",
    "RewardTerm",
    "ScalarizationSpec",
    "ScalarizedStochopiaEnv",
    "Skip",
    "StepTransition",
    "SubmitDesign",
    "SubmitProduct",
    "TrajectoryEntry",
    "TrajectoryMetadata",
    "TrajectoryRecorder",
    "TaskSuite",
    "verify_trajectory",
    "create_api_agent_policy",
    "load_agent_system_prompt",
    "parse_environment_action",
    "run_agent_episode",
    "aggregate_evaluations",
    "load_evaluations",
    "replay_and_evaluate",
    "replay_and_evaluate_payload",
    "save_evaluation_aggregate",
    "scalarize_reward",
]
